### ISSUE TITLE
Include data on logon and idle time

### ISSUE THREAD

**Issue by han44-illinois** [engrit-illinois/Get-ComputersBySessionState#1]
Feature request for the future: include by default or add as an optional flag for the `IDLE TIME` and `LOGON TIME` fields, similar to the output of `quser` e.g.

```
 USERNAME              SESSIONNAME        ID  STATE   IDLE TIME  LOGON TIME
 netid                 console             3  Active      none   8/20/2022 12:00 PM
```

From discussion on Slack, it sounds like qwinsta doesn't capture this data but quser does, so this may require more work than just plugging in new flags for the underlying functions.

**Comment by mmseng** [comment]
See also: https://github.com/engrit-illinois/Get-Sessions/issues/1

**Comment by mmseng** [comment]
Resolved in https://github.com/engrit-illinois/Get-Sessions/commit/699f5aa901538f8908251282cdb27447295ecba9.

**Comment by mmseng** [comment]
Closed the wrong issue.

**Comment by mmseng** [comment]
Resolved in https://github.com/engrit-illinois/Get-ComputersBySessionState/commit/dfb67ccff67c2320e9f5d133a66ef2e748de1a74
